# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{array_stats}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Koski"]
  s.date = %q{2010-04-05}
  s.description = %q{Easy mean, median, percentile, and sum statistics for Ruby Arrays}
  s.email = %q{gems@benkoski.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "array_stats.gemspec",
     "lib/array_stats.rb",
     "lib/array_stats/array.rb",
     "lib/array_stats/array_stats.rb",
     "lib/array_stats/float.rb",
     "test/test_array_stats.rb",
     "test/test_float_extensions.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/bkoski/array_stats}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy mean, median, percentile, and sum statistics for Ruby Arrays}
  s.test_files = [
    "test/test_array_stats.rb",
     "test/test_float_extensions.rb",
     "test/test_helper.rb"
  ]
  s.extensions    = ["ext/array_stats/extconf.rb"]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
